---
title: "extras"
author: "Gabe and Jake"
date: "Tuesday, July 28, 2015"
output: pdf_document
---


```{r,echo=FALSE}
# Loading the most recent results.
library(data.table)
library(bit64)
library(dplyr)
library(ggplot2)
library(tidyr)

df <- fread('results.csv', header=T)
```



```{r, echo=FALSE}
# Cleaning down the data table:
d <- df[,list(ba=ba,nba=nba,bna=bna,nbna=nbna,
              vspeak=verifiedSpeaker,vreply=verifiedReplier,
              sid=speakerId,rid=replierId,category=category,
              pyalign=alignment,reciprocity=reciprocity,numUtterances=numUtterances, msgSentiment=msgSentiment, replySentiment=replySentiment),]

```


```{r}
smoothalign <- function(df,sm,align="logodds") {
  if (align=="logodds") {
    return(log(df$ba+sm)-log(df$ba+df$nba+2*sm)-log(df$bna+sm)+log(df$bna+df$nbna+2*sm))
  } else if (align=="subodds") {
    return((df$ba+sm)/(df$ba+df$nba+2*sm)-(df$bna+sm)/(df$bna+df$nbna+2*sm))
  } else if (align=="logdnm") {
    return(log(df$ba+sm)-log(df$ba+df$nba+2*sm)-log(df$bna+df$ba+sm)+log(df$nba+df$ba+df$bna+df$nbna+2*sm))
  } else if (align=="subdnm") {
    return((df$ba+sm)/(df$ba+df$nba+2*sm)-(df$bna+df$ba+sm)/(df$nba+df$ba+df$bna+df$nbna+2*sm))
  } else {
    stop("Invalid alignment type.")
  }
} 

d$lo1 <- smoothalign(d,1,"logodds")
d$sd0 <- smoothalign(d,0,"subdnm")

stopifnot(max(abs(d$lo1-d$pyalign))<.00001)
#stopifnot(max(abs(d$sd0-d$dnm))<.00001)


```

***Reciprocity***

```{r}
library(dplyr)
library(ggplot2)

theme_set(theme_grey())

d2 <- d %>%
  filter((ba+nba)>5&(bna+nbna)>5) %>%
  group_by(vspeak,category, vreply) %>%
  summarize(convs=n(),alignment=mean(lo1), reciprocity=reciprocity)

ggplot(d2,aes(x=reciprocity,y=alignment)) + geom_violin()


```
Hmm, from the looks of the plot, it doesn't seem like reciprocity has any very much of an impact on alignment

Let's do a t-test

```{r}

t.test(d2$alignment~d2$reciprocity)

```

Interesting..., so there is a huge impact of reciprocity on alignment. .


***Sentiment***

```{r}
library(dplyr)
library(ggplot2)

theme_set(theme_grey())

d2 <- d %>%
  filter((ba+nba)>5&(bna+nbna)>5) %>%
  group_by(vspeak, vreply, category) %>%
  summarize(convs=n(),mean=mean(lo1), msgSentiment=(mean(msgSentiment)>0), replySentiment=(mean(replySentiment)>0))

ggplot(d2,aes(x=msgSentiment,y=mean)) + geom_violin() + facet_wrap(~replySentiment)
```

Clearly, there's an impact of sentiment on alignment. Let's do a t-test

```{r}

d2 <- d %>%
  filter((ba+nba)>5&(bna+nbna)>5) %>%
  group_by(vspeak, vreply, category) %>%
  summarize(convs=n(),mean=mean(lo1), msgSentiment=(mean(msgSentiment)>0), replySentiment=(mean(replySentiment)>0))

t.test(d2$mean~d2$msgSentiment)

t.test(d2$mean~d2$replySentiment)

mean(filter(d2, msgSentiment==TRUE&replySentiment==TRUE)$mean)

mean(filter(d2, msgSentiment==TRUE&replySentiment==FALSE)$mean)

mean(filter(d2, msgSentiment==FALSE&replySentiment==TRUE)$mean)

mean(filter(d2, msgSentiment==FALSE&replySentiment==FALSE)$mean)

```

*** Shuffling ***

```{r}

df <- fread('test_results1.csv', header=T)

# Cleaning down the data table:
d <- df[,list(ba=ba,nba=nba,bna=bna,nbna=nbna,
              vspeak=verifiedSpeaker,vreply=verifiedReplier,
              sid=speakerId,rid=replierId,category=category,
              pyalign=alignment,numUtterances=numUtterances),]

smoothalign <- function(df,sm,align="logodds") {
  if (align=="logodds") {
    return(log(df$ba+sm)-log(df$ba+df$nba+2*sm)-log(df$bna+sm)+log(df$bna+df$nbna+2*sm))
  } else if (align=="subodds") {
    return((df$ba+sm)/(df$ba+df$nba+2*sm)-(df$bna+sm)/(df$bna+df$nbna+2*sm))
  } else if (align=="logdnm") {
    return(log(df$ba+sm)-log(df$ba+df$nba+2*sm)-log(df$bna+df$ba+sm)+log(df$nba+df$ba+df$bna+df$nbna+2*sm))
  } else if (align=="subdnm") {
    return((df$ba+sm)/(df$ba+df$nba+2*sm)-(df$bna+df$ba+sm)/(df$nba+df$ba+df$bna+df$nbna+2*sm))
  } else {
    stop("Invalid alignment type.")
  }
} 

d$lo1 <- smoothalign(d,1,"logodds")

d2 <- d %>%
  filter((ba+nba)>5&(bna+nbna)>5) %>%
  group_by(vspeak, vreply, category) %>%
  summarize(convs=n(),alignment=mean(lo1))

ggplot(d2, aes(x=vreply, y=alignment)) + geom_violin() + facet_wrap(~vspeak)

```

