---
title: "Coordination in Conversation"
author: "Dan Yurovsky, Aaron Chuey, Jake Prasad, & Gabe Doyle"
date: "July 1, 2015"
output:
  html_document:
    highlight: tango
    theme: spacelab
---
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(message=FALSE, warning=FALSE, cache=TRUE)
```

Load libraries
```{r libraries, cache = FALSE}
library(ggplot2)
library(langcog)
library(readr)
library(cowplot)
```

```{r load_data}
twitter.data <- fread('results.csv') 
childes.data <- fread('test_run1.csv') %>%
  mutate(alignment = as.numeric(ifelse(alignment == "undefined",
                                       NA,alignment)))

# User info for twitter data
userinfo <- read_delim('pairedtweets1000.txt.userinfo',delim='\t') %>%
  mutate(uid = as.character(uid)) %>%
  select(uid,verified,numfollowers) %>%
  mutate(tophalf.followers = numfollowers > median(numfollowers,na.rm=T))
```

```{r munge_data}
childes.alignment <- childes.data %>%
  group_by(speaker,replier,marker) %>%
  summarise(alignment = mean(alignment,na.rm=T)) #mean across markers

twitter.alignment <- twitter.data %>%
  group_by(speaker.id,replier.id,marker) %>%
  summarise(alignment = mean(alignment)) %>%
  mutate(speaker.id.char = as.character(speaker.id),
         replier.id.char = as.character(replier.id)) %>% #bit.64 issues
  ungroup() %>%
  select(-speaker.id,replier.id) %>%
  group_by(speaker.id.char,replier.id.char) %>%
  summarise(alignment = mean(alignment))

# Make copies of userinfo columns for joining
userinfo.speaker <- userinfo %>%
  rename(speaker.id.char = uid,
         verified.speaker = verified,
         numfollowers.speaker = numfollowers,
         tophalf.followers.speaker = tophalf.followers)
userinfo.replier <- userinfo %>%
  rename(replier.id.char = uid,
         verified.replier = verified,
         numfollowers.replier = numfollowers,
         tophalf.followers.replier = tophalf.followers)

# Add userinfo data to alignments 
twitter.info.alignment <- left_join(twitter.alignment,
                                    userinfo.speaker,copy=TRUE) %>%
  left_join(userinfo.replier, copy=TRUE)
```

Compute alignments by userinfo
```{r comparison}
twitter.verified.comp <- twitter.info.alignment %>%
  filter(!is.na(verified.speaker),!is.na(verified.replier)) %>%
  group_by(verified.speaker,verified.replier) 

twitter.verified.comp <- twitter.verified.comp %>%
  summarise(mean = mean(alignment)) %>%
  left_join(multi_boot(twitter.verified.comp,column="alignment",
           statistics_functions = c("ci_lower","ci_upper")),copy=TRUE)

twitter.numfollowers.comp <- twitter.info.alignment %>%
   filter(!is.na(tophalf.followers.speaker),
          !is.na(tophalf.followers.replier)) %>%
  group_by(tophalf.followers.speaker,tophalf.followers.replier)

twitter.numfollowers.comp <- twitter.numfollowers.comp %>%
  summarise(mean = mean(alignment)) %>%
  left_join(multi_boot(twitter.numfollowers.comp,column="alignment",
           statistics_functions = c("ci_lower","ci_upper")),copy=TRUE)
```

Plot
```{r plots,fig.width=5,fig.height=4}
ggplot(aes(x = verified.replier, y = mean, 
           color = verified.speaker,label=verified.speaker),
       data=twitter.verified.comp) +
  geom_pointrange(aes(ymin=ci_lower,ymax = ci_upper),position=position_dodge(.5)) +
  scale_y_continuous(name = "Cooridnation Score") +
  scale_x_discrete(name = "Replier Verified") +
  theme(legend.position=c(.8,.8))

ggplot(aes(x = tophalf.followers.replier, y = mean, 
           color = tophalf.followers.speaker,label=tophalf.followers.speaker),
       data=twitter.numfollowers.comp) +
  geom_pointrange(aes(ymin=ci_lower,ymax = ci_upper),position=position_dodge(.5)) +
  scale_y_continuous(name = "Cooridnation Score") +
  scale_x_discrete(name = "Replier >Median Followers") +
  theme(legend.position=c(.8,.2))
```
