---
title: "Coordination in Childes"
author: "Dan Yurovsky, Aaron Chuey, Jake Prasad, & Gabe Doyle"
date: "August 10, 2015"
output:
  html_document:
    highlight: tango
    theme: spacelab
---
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(message=FALSE, warning=FALSE, cache=TRUE)
```

Load libraries
```{r libraries, cache = FALSE}
library(ggplot2)
library(data.table)
library(dplyr)
library(langcog)
library(readr)
library(cowplot)
library(tidyr)
library(stringr)
library(magrittr)
library(directlabels)
library(lubridate)
library(lme4)
library(lmerTest)
```

```{r useful_functions}
convert.age <- function(childes.age) {
  age <- as.numeric(unlist(strsplit(childes.age, "[PYMD]"))[2:4])
  age[2] <- ifelse(is.na(age[2]), 0, age[2])
  age[3] <- ifelse(is.na(age[3]), 0, age[3])
 
  return((age[1]*365+age[2]*30.5+age[3])/30.5)
}

read.data.file <- function(file) {
  read_csv(paste0('../Childes_Results/', file)) %>%
    mutate(type = ifelse(str_count(file,"Stem") > 0, "Stemmed", "Unstemmed")) %>%
    rename(marker = category)
}

read.marker.file <- function(file) {
  read_csv(paste0('../Marker_Lists/', file)) %>%
    mutate(type = ifelse(str_count(file,"Stem") > 0, "Stemmed", "Unstemmed"),
           corpus = sub("Marker.*","",file),"") %>%
    select(Word,Frequency,type,corpus) %>%
    rename(marker = Word)
}

```

```{r load_data}
userinfo.files <- list.files(path = "../Childes_userinfo", 
                            pattern = '*.csv', all.files = FALSE)

result.files <- list.files(path = "../Childes_results", 
                            pattern = '*.csv', all.files = FALSE)

marker.files <- list.files(path = "../Marker_Lists/", 
                            pattern = '*Freq.csv', all.files = FALSE)



childes.userinfo <- bind_rows(lapply(userinfo.files, function(file) {
                                       read_csv(paste0('../Childes_userinfo/',
                                                       file))})) %>%
  rename(Child = role) %>%
  rowwise() %>%
  mutate(Age = convert.age(Age))

childes.markers <- bind_rows(lapply(marker.files, read.marker.file))

childes.results <- bind_rows(lapply(result.files, read.data.file)) %>%
  rename(DocId = docId)
```

```{r munge_data}
childes.data <- left_join(childes.results,childes.userinfo) %>%
  left_join(childes.markers) %>%
  rename(Speaker = speakerId, Replier = replierId) %>%
  filter(Speaker %in% c("CHI", "MOT"), Replier %in% c("CHI", "MOT")) %>%
  group_by(type,Child,Age,Replier)
```

```{r models}

lm1 <- lmer(alignment ~ Age * Replier + type + log(Frequency) + 
              (Replier | Child) + (Replier | marker) ,
            data = childes.data)

childes.data$align.predict <- predict(lm1)

lm2 <- lmer(dnmalignment ~ Age * Replier + type + log(Frequency) + (Replier|Child),
            data = childes.data)
```

```{r summaries}
childes.alignment <- multi_boot_standard(childes.data, "alignment", na.rm = TRUE) %>%
  left_join(summarise(childes.data,align.predict = mean(align.predict, na.rm = TRUE)))

childes.dnmalignment <- multi_boot_standard(childes.data, "dnmalignment", na.rm = TRUE)
```


```{r plot}
#Stemmed
ggplot(aes(x = Age,y = mean, color = Replier), 
       data = filter(childes.alignment,type == "Stemmed")) +
  facet_wrap(~ Child) +
  geom_smooth(method = "loess")+
  geom_line(aes(y = align.predict),size = 2)+
  geom_hline(yintercept=0,lty=2) +
  geom_pointrange(aes(ymax = ci_upper, ymin = ci_lower),size = .25) +
  scale_color_brewer(palette = "Set1") +
  theme(legend.position = "none") +
  scale_x_continuous(limits=c(10,60),breaks=seq(10,50,10))+
  geom_dl(aes(label=Replier),method=list("last.points",cex=.8,dl.trans(x=x +.2)))

#Unstemmed
ggplot(aes(x = Age,y = mean, color = Replier), 
       data = filter(childes.alignment,type == "Unstemmed")) +
  facet_wrap( ~ Child) +
  geom_smooth(method = "loess")+
  geom_hline(yintercept=0,lty=2) +
  geom_pointrange(aes(ymax = ci_upper, ymin = ci_lower)) +
  scale_color_brewer(palette = "Set1") +
  theme(legend.position = "none") +
  scale_x_continuous(limits=c(10,60),breaks=seq(10,50,10))+
  geom_dl(aes(label=Replier),method=list("last.points",cex=.8,dl.trans(x=x +.2)))
```

```{r dnm_plot}
#Stemmed
ggplot(aes(x = Age,y = mean, color = Replier), 
       data = filter(childes.dnmalignment,type == "Stemmed")) +
  facet_wrap(~ Child) +
  geom_smooth(method = "loess")+
  geom_hline(yintercept=0,lty=2) +
  geom_pointrange(aes(ymax = ci_upper, ymin = ci_lower)) +
  scale_color_brewer(palette = "Set1") +
  theme(legend.position = "none") +
  scale_x_continuous(limits=c(10,60),breaks=seq(10,50,10))+
  geom_dl(aes(label=Replier),method=list("last.points",cex=.8,dl.trans(x=x +.2)))

#Unstemmed
ggplot(aes(x = Age,y = mean, color = Replier), 
       data = filter(childes.dnmalignment,type == "Unstemmed")) +
  facet_wrap( ~ Child) +
  geom_smooth(method = "loess")+
  geom_hline(yintercept=0,lty=2) +
  geom_pointrange(aes(ymax = ci_upper, ymin = ci_lower)) +
  scale_color_brewer(palette = "Set1") +
  theme(legend.position = "none") +
  scale_x_continuous(limits=c(10,60),breaks=seq(10,50,10))+
  geom_dl(aes(label=Replier),method=list("last.points",cex=.8,dl.trans(x=x +.2)))
```